### ISSUE TITLE
Module not found: Can't resolve 'flickity'

### ISSUE THREAD

**Issue by KZTN** [theolampert/react-flickity-component#107] opened 2020-06-28 16:38 UTC
I recently start to use this dependency in my projects. When I tried to import to my page using ES2015 it's showing that  the module can't be found.

```
Failed to compile

./node_modules/react-flickity-component/lib/index.js
Module not found: Can't resolve 'flickity' in '/home/kztn/Documents/Portfolio/node_modules/react-flickity-component/lib'
```
But this file Can be found navigating by the node_modules
![Screenshot from 2020-06-28 13-30-41](https://user-images.githubusercontent.com/6463299/85953068-45e87b80-b944-11ea-9d9d-d8e8e1ac3c03.png)

My attempts to solve this problem:
Removed ant re-added the dependency
Move the project folter to another directory

Flickity version used: ^3.5.0
React version: ^16.13.1
Yarn version: 1.22.4
Node version: 13.12.0
OS: Ubuntu 20.04 LTS

**Comment by zd4y** [comment] 2020-06-28 23:45
I am having the same problem on a newly created project using `npx create-react-app .` and installing it with `npm i react-flickity-component`. I am using the same version of react and react-flickity-component but npm 6.14.5 and node 14.3.0 on manjaro. I can also find the folder navigating by the node_modules and I am importing it using `import Flickity from 'react-flickity-component'`

**Comment by zd4y** [comment] 2020-06-29 21:30
Hey @KZTN , this is annoying but just use version `3.4.0`. It works fine :D

**Comment by Jebble** [comment] 2020-07-08 13:44
Duplicate of #96 

Install flickity seperate will fix.

**Closed** 2020-07-14 14:46 UTC

**Comment by martinrojas** [comment] 2022-03-01 16:32
should the documentation not be updated that flickity should be installed separately now

**Comment by yaodingyd** [comment] 2022-03-01 17:59
document updated
